# AUTO-GENERATED FILE — DO NOT EDIT BY HAND
# Generated by gameDataClasses.write_constants_file()

# Constants (manual) assorted 
MAXDISTANCE = 5

# Constants (manual) for unitHexes 2nd dim (hex coords) and new table from flattening UnitTerrainAltitudes
X = 0
Y = 1
ALT = 2

# Constants (manual) for new table from flattening COMBAT 
AP = 0
DP = 1

# Constants for Abilities
RECORDEXISTS = 0
REQUIRESACTION = 1
DEFAULT = 2
ALLOWMOVEMENT = 3

# Constants for Altitudes
ATTACKBONUS = 0

# Constants for Maptags
NAME = 0

# Constants for Races
NAME = 0

# Constants for TerrainAltitudes
ALLOWED = 0

# Constants for Terrains
NAME = 0

# Constants for UnitAbilities
RECORDEXISTS = 0
COOLDOWN = 1
ABILITYSTRENGTH = 2

# Constants for UnitAltitudes
MOBILITY = 0
VISION = 1
ATTACKRANGEMIN = 2
ATTACKRANGEMAX = 3
DEFENSE = 4

# Constants for Units
RACENUMBER = 0
COST = 1
UNITTYPENUMBER = 2
REPAIR = 3
ACTIONSPERTURN = 4

# Constants for UnitTerrains
ATTACKBONUS = 0
DEFENSEBONUS = 1
MOVEMENTALLOWED = 2
MOBILITYCOST = 3

# Constants for Unittypes
NAME = 0

# Constants for UnittypeTerrains
ATTACKBONUS = 0
DEFENSEBONUS = 1
MOVEMENTALLOWED = 2
MOBILITYCOST = 3

# Constants for UnitUnittypeAltitudes
STRENGTH = 0
ARMORPIERCING = 1

