import os
import re

from src.data.gameDataClasses import clsGameData, gamedata_raw_structure
import src.data.generated_constants as gc
import src.errorHandler as eh

#maybe bundle this with other utils instead
#should WRITE ALL FIELDS OF ALL DATACLASSES (at least the ones with simple parts - namely clsLoc)
#add terrains numbers!
def write_constants_file(GameData: clsGameData):
    """
    Generate a Python file containing hardcoded constants for all packed columns
    so the IDE can autocomplete them.
    """

    output_path = "src/data/generated_constants.py"
    constant_dict = {}

    lines = []
    lines.append("# AUTO-GENERATED FILE — DO NOT EDIT BY HAND\n")
    lines.append("# Generated by gameDataClasses.write_constants_file()\n\n")

    #MANUAL
    constant_dict = {"MAXDISTANCE": 5, "X": 0, "Y": 1, "ALT": 2, "DEFAULTALTITUDE": 1} #from manual

    lines.append(f"# Constants (manual) assorted \n")
    lines.append(f"MAXDISTANCE = 5\n") #max distance of ranged attack (walker). Could actually get this from GameData... ugh. Contants not needed for loader.
    lines.append("\n")

    lines.append(f"# Constants (manual) for unitHexes 2nd dim (hex coords) and new table from flattening UnitTerrainAltitudes\n")
    lines.append(f"X = 0\n")
    lines.append(f"Y = 1\n")
    lines.append(f"ALT = 2\n")
    lines.append(f"DEFAULTALTITUDE = 1")
    lines.append("\n")

    # lines.append(f"# Constants (manual) for new table from flattening COMBAT \n")
    # lines.append(f"AP = 0\n")
    # lines.append(f"DP = 1\n")
    # lines.append("\n")

    #AUTOMATIC

    # Iterate through raw structure
    lines.append(f"# Constants for each source table\n")
    for d in gamedata_raw_structure:
        
        # Optional: write a section header
        if "name" in d:
            lines.append(f"# Constants for {d['name']}\n")

        packed_cols = d["packed_cols"]
        for i, packed_col in enumerate(packed_cols):
            const_name = packed_col.strip().upper().replace(" ", "_")
            if const_name in constant_dict:
                if constant_dict[const_name] != i: raise RuntimeError(f"{const_name} is duplicate with conflicting values")
            else:
                constant_dict[const_name] = i
            lines.append(f"{const_name} = {i}\n")

        lines.append("\n") #space before next section

    #ABILITY NUMBERS, terrains, altitudes??
    if os.path.exists(output_path): #only run if gc.Name already exists in file

        names_to_write = {
            "Abilities": GameData.Abilities_Name
            , "Terrains": GameData.Terrains_Name
            , "Altitudes": GameData.Altitudes_Name
            , "Races": GameData.Races_Name
            , "Unittypes": GameData.Unittypes_Name
        }

        for listname, namelist in names_to_write.items():
            lines.append(f"# Constants for {listname} numbers \n")
            for i, row in enumerate(namelist):
                if i == 0: continue #we don't have a 0-indexed ability, we start at 1 because we're weird
                const_name: str = str(row[gc.NAME])
                # const_name = re.sub(r"\s+", "_", const_name.strip()) #replace internal spaces (of any chain length) with an underscore
                const_name = "".join(const_name.split()) #removes spaces, tabs, and newlines
                const_name = const_name.upper()
                if const_name in constant_dict:
                    if constant_dict[const_name] != i: eh.error(f"{const_name} is duplicate with conflicting values")
                else:
                    constant_dict[const_name] = i
                lines.append(f"{const_name} = {i}\n")
            lines.append("\n")


    # Write / overwrite the file
    with open(output_path, "w", encoding="utf-8") as f:
        f.writelines(lines)

    # print(f"Generated constants file at: {os.path.abspath(output_path)}")